# Generated by Django 4.2.6 on 2023-11-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_regions_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('regions_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Regions number')),
            ],
        ),
        migrations.AlterField(
            model_name='visit',
            name='museum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myapp.district'),
        ),
        migrations.DeleteModel(
            name='Museum',
        ),
    ]
