# Generated by Django 4.2.6 on 2023-11-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_objects_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects_main',
            name='images',
            field=models.ImageField(help_text='Rasmi', null=True, unique=True, upload_to='*'),
        ),
    ]
