# Generated by Django 4.2.6 on 2023-11-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_objects_main_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects_main',
            name='images',
            field=models.FileField(help_text='Rasmi', null=True, unique=True, upload_to='.'),
        ),
    ]
