# Generated by Django 4.2.7 on 2023-11-30 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_objects_main_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='regions_id',
        ),
        migrations.AddField(
            model_name='district',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myapp.regions'),
        ),
    ]
