# Generated by Django 4.2.7 on 2023-11-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_district_regions_id_district_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='category',
            new_name='regions_id',
        ),
    ]
