# Generated by Django 4.2.7 on 2023-12-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_objects_main_rented_alter_objects_main_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects_contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('district_name', models.CharField(max_length=100, null=True)),
                ('region_id', models.CharField(max_length=100, null=True)),
                ('district_id', models.CharField(max_length=100, null=True)),
                ('contract_number', models.CharField(max_length=100, null=True)),
                ('contract_date', models.FileField(null=True, upload_to='.')),
                ('start_date', models.CharField(max_length=100, null=True)),
                ('end_date', models.CharField(max_length=100, null=True)),
                ('ap_start', models.CharField(max_length=100, null=True)),
                ('ap_end', models.CharField(max_length=100, null=True)),
                ('taq', models.CharField(max_length=100, null=True)),
                ('imt', models.CharField(max_length=100, null=True)),
                ('k_number', models.CharField(max_length=100, null=True, unique=True)),
                ('contract_event', models.CharField(max_length=100, null=True)),
                ('yanvar', models.CharField(max_length=100, null=True)),
                ('fevral', models.CharField(max_length=100, null=True)),
                ('mart', models.CharField(max_length=100, null=True)),
                ('aprel', models.CharField(max_length=100, null=True)),
                ('may', models.CharField(max_length=100, null=True)),
                ('iyun', models.CharField(max_length=100, null=True)),
                ('iyul', models.CharField(max_length=100, null=True)),
                ('avgust', models.CharField(max_length=100, null=True)),
                ('sentabr', models.CharField(max_length=100, null=True)),
                ('oktabr', models.CharField(max_length=100, null=True)),
                ('noyabr', models.CharField(max_length=100, null=True)),
                ('dekabr', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
