# Generated by Django 4.2.7 on 2023-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_objects_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects_contract',
            name='auk_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='auk_cont',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='auk_lot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='auth_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='auth_bank',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='auth_mfo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='auth_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='auth_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='auth_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='auth_price_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='auth_str',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='cont_auth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='contract_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='mfo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_cont_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_district_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_district_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_f_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_f_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_ij_st',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_im_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_kx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_kz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_min_kv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_region_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_regions_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_year_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='obj_year_stavka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='str_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects_contract',
            name='xisob_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
