# Generated by Django 4.2.7 on 2023-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_objects_contract_auk_area_objects_contract_auk_cont_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects_main',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
