# Generated by Django 4.2.7 on 2023-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_objects_main_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects_main',
            name='address_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
