# Generated by Django 4.2.7 on 2023-12-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_objects_main_address_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objects_main',
            old_name='images',
            new_name='images1',
        ),
        migrations.AddField(
            model_name='objects_main',
            name='images2',
            field=models.FileField(null=True, upload_to='.'),
        ),
        migrations.AddField(
            model_name='objects_main',
            name='images3',
            field=models.FileField(null=True, upload_to='.'),
        ),
        migrations.AddField(
            model_name='objects_main',
            name='images4',
            field=models.FileField(null=True, upload_to='.'),
        ),
        migrations.AddField(
            model_name='objects_main',
            name='images5',
            field=models.FileField(null=True, upload_to='.'),
        ),
    ]
