# Generated by Django 4.2.7 on 2023-12-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_images_objects_main_images1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects_main',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
